export const whapFacts = [
  'Did you know? The Silk Road connected China and the Roman Empire.',
  'Fun fact: The printing press was invented in 1440 by Johannes Gutenberg.',
  'Interesting: The Renaissance began in Italy in the late 14th century.',
  'History note: The French Revolution started in 1789.',
  'WHAP fact: The Industrial Revolution began in Britain in the 18th century.',
  'Fact: The Byzantine Empire preserved Greek and Roman culture after the fall of Rome.',
  'Did you know? The Ottoman Empire lasted from 1299 to 1922.',
  "Fun fact: The Meiji Restoration in 1868 marked Japan's modernization.",
  'History note: The Mughal Empire ruled most of India from the early 16th to the mid-18th century.',
  'WHAP fact: The Black Death killed an estimated 75-200 million people in the 14th century.',
  'Did you know? The Aztec Empire was centered in what is now Mexico City.',
  'Interesting: The Enlightenment promoted ideas of individual rights and reason.',
  'History note: The Berlin Conference of 1884-1885 regulated European colonization of Africa.',
  'WHAP fact: The Mayan civilization developed advanced writing and astronomical systems.',
  'Fun fact: The fall of Constantinople in 1453 marked the end of the Byzantine Empire.',
  'Did you know? The Taj Mahal was completed in 1653 by Mughal Emperor Shah Jahan.',
  'Interesting: The Suez Canal was opened in 1869, connecting the Mediterranean Sea to the Red Sea.',
  'History note: The Persian Empire was known for its tolerance and efficient administration.',
  'WHAP fact: The Viking Age lasted from the late 8th century to the early 11th century.',
  'Fun fact: The Great Wall of China was built to protect against invasions from northern tribes.',
  'Did you know? The Inca Empire was the largest empire in pre-Columbian America.',
  'Interesting: The Reformation in the 16th century led to significant changes in the Christian Church.',
  'History note: The Treaty of Versailles ended World War I in 1919.',
  'WHAP fact: The Opium Wars in the mid-19th century opened China to Western trade and influence.',
  'Fun fact: The Korean War (1950-1953) ended in an armistice, not a peace treaty.',
];
